[package]
name = "rom-res-rs"
version = "0.1.1"
authors = ["madwareru <madware.ru@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cp866-rs = { git = "https://github.com/madwareru/cp866-rs", version = "0.1.2"}

[dev-dependencies]
quad-snd = { git = "https://github.com/not-fl3/quad-snd", version = "0.1.0"}
bin-serialization-rs = { git = "https://github.com/madwareru/bin-serialization-rs", version = "0.1.3"}
rom-loaders-rs = { git = "https://github.com/madwareru/rom-loaders-rs", version = "0.1.1"}
wav = "0.4.0"
regex = "1.3.9"