[package]
name = "rom-res-rs"
version = "0.1.1"
authors = ["madwareru <madware.ru@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cp866-rs = { git = "https://github.com/madwareru/cp866-rs", version = "0.1.2"}

[dev-dependencies]
rom-media-rs = { git = "https://github.com/madwareru/rom-media-rs", version = "0.2.9" }
bin-serialization-rs = { git = "https://github.com/madwareru/bin-serialization-rs", version = "0.1"}
rom-loaders-rs = { git = "https://github.com/madwareru/rom-loaders-rs", version = "0.2.37"}
regex = "1.3.9"
macroquad = "0.2.0-alpha.0"
minifb = "0.19.1"